### ISSUE TITLE
support segwit transation ？ or segwit sign？

### ISSUE THREAD

**Issue by sinorychan** [kishikawakatsumi/BitcoinKit#147]
# Current behavior

# Expected behavior

# Steps to reproduce
1. 
2. 
3. 

# Environment

- BitcoinKit: *?.?*
- Xcode Version: *?.? (????)*
- Swift Version: *?.?*

**Comment by DiwakarThapa** [comment]
testnet-seed.bitcoin.jonasschnelli.ch:18333 sending tx
testnet-seed.bitcoin.jonasschnelli.ch:18333 sending getblocks
testnet-seed.bitcoin.jonasschnelli.ch:18333 got inv with 1 item(s)
testnet-seed.bitcoin.jonasschnelli.ch:18333 sending getdata
testnet-seed.bitcoin.jonasschnelli.ch:18333 rejected tx code: 0x10 reason: bad-txns-inputs-duplicate, data:  

These error caused by segwit , Isn't it? . Those errors occurs in my console when I send transaction using testnetBTC.
